=begin
#Gong API



OpenAPI spec version: V2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.37
=end

require 'spec_helper'
require 'json'

# Unit tests for GongAPI::CallsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CallsApi' do
  before do
    # run before each test
    @instance = GongAPI::CallsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CallsApi' do
    it 'should create an instance of CallsApi' do
      expect(@instance).to be_instance_of(GongAPI::CallsApi)
    end
  end

  # unit tests for add_call_recording_using_put
  # Add call media (/v2/calls/{id}/media)
  # Adds a call media, recorded by a telephony system (PBX) or other media recording facility. Gong accepts call recordings in various audio and video file formats, including WAV, MP3, MP4, MKV and FLAC. If uploading a dual-channel (stereo) file separated by speaker, make sure to specify which channel correspondsto the company team member (rep) in the parties/mediaChannelId parameter of the Add New Call operation.  When accessed through a Bearer token authorization method, this endpoint requires the scope &#x27;api:calls:create&#x27;.
  # @param id callId returned from &#x27;Add New Call&#x27; request
  # @param [Hash] opts the optional parameters
  # @option opts [String] :media_file 
  # @return [NewCallRecordingResponse]
  describe 'add_call_recording_using_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for add_call_using_post
  # Add new call (/v2/calls)
  # When using this endpoint, either provide a downloadMediaUrl or use the returned callId in a follow-up request to /v2/calls/{id}/media to upload the media file.  When accessed through a Bearer token authorization method, this endpoint requires the scope &#x27;api:calls:create&#x27;.
  # @param body newCallAddingRequest
  # @param [Hash] opts the optional parameters
  # @return [NewCallAddingResponse]
  describe 'add_call_using_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_call_transcripts_using_post
  # Retrieve transcripts of calls by date or callIds (/v2/calls/transcript)
  # Lists the transcripts of calls that took place during a specified date range and have specified callIds.  When accessed through a Bearer token authorization method, this endpoint requires the scope &#x27;api:calls:read:transcript&#x27;.
  # @param body callsRequest
  # @param [Hash] opts the optional parameters
  # @return [CallTranscripts]
  describe 'get_call_transcripts_using_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_call_using_get
  # Retrieve data for a specific call (/v2/calls/{id})
  # Retrieve data for a specific call.  When accessed through a Bearer token authorization method, this endpoint requires the scope &#x27;api:calls:read:basic&#x27;.
  # @param id Gong&#x27;s unique numeric identifier for the call (up to 20 digits).
  # @param [Hash] opts the optional parameters
  # @return [SpecificCall]
  describe 'get_call_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_calls_extensive_using_post
  # Retrieve detailed call data by various filters (/v2/calls/extensive)
  # Lists detailed call data for calls that took place during a specified date range, have specified call IDs or hosted by specified users.  When accessed through a Bearer token authorization method, this endpoint requires the scope &#x27;api:calls:read:extensive&#x27;.  Moreover, clients requesting media download URLs by the contentSelector.exposedFields.media field should also have the scope &#x27;api:calls:read:media-url&#x27;.
  # @param body callsRequest
  # @param [Hash] opts the optional parameters
  # @return [Calls]
  describe 'list_calls_extensive_using_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_calls_using_get
  # Retrieve call data by date range (/v2/calls)
  # List calls that took place during a specified date range.  When accessed through a Bearer token authorization method, this endpoint requires the scope &#x27;api:calls:read:basic&#x27;.
  # @param from_date_time The date from which to list calls, in the ISO-8601 format (e.g., &#x27;2018-02-18T02:30:00-07:00&#x27; or &#x27;2018-02-18T08:00:00Z&#x27;, where Z stands for UTC); if not specified, the calls start with the earliest recorded call. For web-conference calls recorded by Gong, the date denotes its scheduled time, otherwise, it denotes its actual start time.
  # @param to_date_time The date until which to list calls, in the ISO-8601 format (e.g., &#x27;2018-02-18T02:30:00-07:00&#x27; or &#x27;2018-02-18T08:00:00Z&#x27;, where Z stands for UTC); if not specified, the calls end with the latest recorded call. For web-conference calls recorded by Gong, the date denotes its scheduled time, otherwise, it denotes its actual start time.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor When paging is needed, provide the value supplied by the previous API call to bring the following page of records.
  # @option opts [String] :workspace_id Optional Workspace identifier, if supplied the API will return only the calls belonging to this workspace.
  # @return [CallsResponse]
  describe 'list_calls_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_crm_calls_manual_association_using_get
  # List all calls that were manually associated with CRM objects (/v2/calls/manual-crm-associations) in Beta Phase
  # Returns a list of all calls that were manually associated or re-associated with CRM account and deal/opportunity since a given time.  Actions will be listed in the ascending order of their timing.   Notice if a call was associated and later re-associated the API will return both events.  When accessed through a Bearer token authorization method, this endpoint requires the scope &#x27;api:crm-calls:manual-association:read&#x27;.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor When paging is needed, provide the value supplied by the previous API call to bring the following page of records.
  # @option opts [String] :from_date_time Association time filter - only the associations made after that time will be listed. The time is in the ISO-8601 format (e.g., &#x27;2018-02-18T02:30:00-07:00&#x27; or &#x27;2018-02-18T08:00:00Z&#x27;, where Z stands for UTC); if not specified all association events will be listed.
  # @return [ManualAssociationResponse]
  describe 'list_crm_calls_manual_association_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
