=begin
#Gong API



OpenAPI spec version: V2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.37
=end

require 'spec_helper'
require 'json'

# Unit tests for GongAPI::DataPrivacyApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DataPrivacyApi' do
  before do
    # run before each test
    @instance = GongAPI::DataPrivacyApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DataPrivacyApi' do
    it 'should create an instance of DataPrivacyApi' do
      expect(@instance).to be_instance_of(GongAPI::DataPrivacyApi)
    end
  end

  # unit tests for find_all_references_to_email_address_using_get
  # Retrieve all references to an email address. (/v2/data-privacy/data-for-email-address)
  # Shows the elements in the Gong system that reference the given email address. Given an emails address, this endpoint returns details of all calls and email messages that reference this address, and any leads or contacts with this email address.  When accessed through a Bearer token authorization method, this endpoint requires the scope &#x27;api:data-privacy:read&#x27;.
  # @param email_address The email address.
  # @param [Hash] opts the optional parameters
  # @return [EmailAddressReferences]
  describe 'find_all_references_to_email_address_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_all_references_to_phone_number_using_get
  # Retrieve all references to a phone number. (/v2/data-privacy/data-for-phone-number)
  # Shows the elements in the Gong system that reference the given phone number. Given a phone number, this endpoint returns details of any leads or contacts with this phone number and their associated calls and email messages.  When accessed through a Bearer token authorization method, this endpoint requires the scope &#x27;api:data-privacy:read&#x27;.
  # @param phone_number The phone number.  This number must start with a + (plus) sign followed by the country code, area code, and local phone number. All other non-digits are ignored.  The following are examples of permitted phone numbers: +1 425 555 2671, +1-425-555-2671, +1 425 5552671, +14255552671, +1 425 555 26 71, +1(425) 555-2671, etc.  Note: This parameter should be URL-encoded.
  # @param [Hash] opts the optional parameters
  # @return [PhoneNumberReferences]
  describe 'find_all_references_to_phone_number_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for purge_email_address_using_post
  # Delete the email address, and all associated elements (/v2/data-privacy/erase-data-for-email-address)
  # Given an email address, this endpoint deletes from the Gong system any calls or email messages that reference this address. Email messages sent to or from the address are deleted. Calls where the email address appears (as a lead, contact, attendee or speaker) are deleted. Leads or Contacts with the email address are deleted. The deletion is not immediate, and may take several hours to complete.  This endpoint contains a data integrity protection mechanism to prevent the deletion of an abnormal number of objects. If the deletion fails please contact support at help@gong.io  Delete the data from your CRM and email system before performing this operation so that private data is not re-imported into Gong.  When accessed through a Bearer token authorization method, this endpoint requires the scope &#x27;api:data-privacy:delete&#x27;.
  # @param email_address The email address.
  # @param [Hash] opts the optional parameters
  # @return [BaseResponse]
  describe 'purge_email_address_using_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for purge_phone_number_using_post
  # Delete the phone number, and all associated elements (/v2/data-privacy/erase-data-for-phone-number)
  # Given a phone number, this endpoint deletes from the Gong system any leads or contacts with a matching phone number or mobile phone number. Email messages sent to or from these leads/contacts are deleted. Calls where the leads/contacts appear are deleted. The deletion is not immediate, and may take several hours to complete.  This endpoint contains a data integrity protection mechanism to prevent the deletion of an abnormal number of objects. If the deletion fails please contact support at help@gong.io  Delete the data from your CRM and email system before performing this operation so that private data is not re-imported into Gong.  When accessed through a Bearer token authorization method, this endpoint requires the scope &#x27;api:data-privacy:delete&#x27;.
  # @param phone_number The phone number.  This number must start with a + (plus) sign followed by the country code, area code, and local phone number. All other non-digits are ignored.  The following are examples of permitted phone numbers: +1 425 555 2671, +1-425-555-2671, +1 425 5552671, +14255552671, +1 425 555 26 71, +1(425) 555-2671, etc.  Note: This parameter should be URL-encoded.
  # @param [Hash] opts the optional parameters
  # @return [BaseResponse]
  describe 'purge_phone_number_using_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
