=begin
#Gong API



OpenAPI spec version: V2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.37
=end

require 'spec_helper'
require 'json'

# Unit tests for GongAPI::LibraryApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LibraryApi' do
  before do
    # run before each test
    @instance = GongAPI::LibraryApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LibraryApi' do
    it 'should create an instance of LibraryApi' do
      expect(@instance).to be_instance_of(GongAPI::LibraryApi)
    end
  end

  # unit tests for get_calls_in_specific_folder_using_get
  # List of calls in a specific folder (/v2/library/folder-content)
  # Given a folder id, this endpoint retrieves a list of calls in it.  When accessed through a Bearer token authorization method, this endpoint requires the scope &#x27;api:library:read&#x27;.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :folder_id Gong&#x27;s unique numeric identifier for the folder (up to 20 digits).
  # @return [LibraryFolderListOfCallsResponse]
  describe 'get_calls_in_specific_folder_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_library_structure_using_get
  # Retrieve Library folders (/v2/library/folders)
  # Use this endpoint to retrieve a list of public library folders. We do not allow retrieval of either private or archived folders.  When accessed through a Bearer token authorization method, this endpoint requires the scope &#x27;api:library:read&#x27;.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :workspace_id Workspace identifier. We will retrieve folders which are related to this specific workspace.
  # @return [LibraryResponse]
  describe 'get_library_structure_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
