=begin
#Gong API



OpenAPI spec version: V2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.37
=end

require 'spec_helper'
require 'json'

# Unit tests for GongAPI::MeetingsInBetaPhaseApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MeetingsInBetaPhaseApi' do
  before do
    # run before each test
    @instance = GongAPI::MeetingsInBetaPhaseApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MeetingsInBetaPhaseApi' do
    it 'should create an instance of MeetingsInBetaPhaseApi' do
      expect(@instance).to be_instance_of(GongAPI::MeetingsInBetaPhaseApi)
    end
  end

  # unit tests for add_meeting_using_post
  # Create a New Gong Meeting (/v2/meetings)
  # When accessed through a Bearer token authorization method, this endpoint requires the scope &#x27;api:meetings:user:create&#x27;.
  # @param body newMeetingRequest
  # @param [Hash] opts the optional parameters
  # @return [NewMeetingResponse]
  describe 'add_meeting_using_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_meeting_using_delete
  # Delete a Gong Meeting (/v2/meetings)
  # When accessed through a Bearer token authorization method, this endpoint requires the scope &#x27;api:meetings:user:delete&#x27;.
  # @param body request
  # @param meeting_id Gong&#x27;s unique identifier for the meeting (up to 20 digits).
  # @param [Hash] opts the optional parameters
  # @return [DeleteMeetingRequest]
  describe 'delete_meeting_using_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for integration_status_using_post
  # Validate Gong meeting Integration (/v2/meetings/integration/status)
  # When accessed through a Bearer token authorization method, this endpoint requires the scope &#x27;api:meetings:integration:status&#x27;.
  # @param body integrationStatusRequest
  # @param [Hash] opts the optional parameters
  # @return [IntegrationStatusResponse]
  describe 'integration_status_using_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_meeting_using_put
  # Update a Gong Meeting (/v2/meetings/{meetingId})
  # When accessed through a Bearer token authorization method, this endpoint requires the scope &#x27;api:meetings:user:update&#x27;.
  # @param body updateMeetingRequest
  # @param meeting_id Gong&#x27;s unique identifier for the meeting (up to 20 digits).
  # @param [Hash] opts the optional parameters
  # @return [UpdateMeetingResponse]
  describe 'update_meeting_using_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
