=begin
#Gong API



OpenAPI spec version: V2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.37
=end

require 'spec_helper'
require 'json'

# Unit tests for GongAPI::SettingsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SettingsApi' do
  before do
    # run before each test
    @instance = GongAPI::SettingsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SettingsApi' do
    it 'should create an instance of SettingsApi' do
      expect(@instance).to be_instance_of(GongAPI::SettingsApi)
    end
  end

  # unit tests for list_scorecards_using_get
  # Retrieve scorecards details (/v2/settings/scorecards)
  # Retrieve all the scorecards within the Gong system.  When accessed through a Bearer token authorization method, this endpoint requires the scope &#x27;api:settings:scorecards:read&#x27;.
  # @param [Hash] opts the optional parameters
  # @return [Scorecards]
  describe 'list_scorecards_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_workspaces_using_get
  # List all company workspaces (/v2/workspaces)
  # Returns a list of all workspaces including their details.  When accessed through a Bearer token authorization method, this endpoint requires the scope &#x27;api:workspaces:read&#x27;.
  # @param [Hash] opts the optional parameters
  # @return [WorkspacesMetadata]
  describe 'list_workspaces_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
