=begin
#Gong API



OpenAPI spec version: V2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.37
=end

require 'spec_helper'
require 'json'

# Unit tests for GongAPI::UsersApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UsersApi' do
  before do
    # run before each test
    @instance = GongAPI::UsersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UsersApi' do
    it 'should create an instance of UsersApi' do
      expect(@instance).to be_instance_of(GongAPI::UsersApi)
    end
  end

  # unit tests for get_user_history_using_get
  # Retrieve user history (/v2/users/{id}/settings-history)
  # Retrieve a specific user&#x27;s history.  When accessed through a Bearer token authorization method, this endpoint requires the scope &#x27;api:users:read&#x27;.
  # @param id Gong&#x27;s unique numeric identifier for the user (up to 20 digits).
  # @param [Hash] opts the optional parameters
  # @return [SettingsHistory]
  describe 'get_user_history_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_user_using_get
  # Retrieve user (/v2/users/{id})
  # Retrieve a specific user.  When accessed through a Bearer token authorization method, this endpoint requires the scope &#x27;api:users:read&#x27;.
  # @param id Gong&#x27;s unique numeric identifier for the user (up to 20 digits).
  # @param [Hash] opts the optional parameters
  # @return [User]
  describe 'get_user_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_multiple_users_using_post
  # List users by filter (/v2/users/extensive)
  # List multiple Users.  When accessed through a Bearer token authorization method, this endpoint requires the scope &#x27;api:users:read&#x27;.
  # @param body multipleUsersRequest
  # @param [Hash] opts the optional parameters
  # @return [UsersMetadata]
  describe 'list_multiple_users_using_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_users_using_get
  # List all users (/v2/users)
  # List all of the company&#x27;s users.  When accessed through a Bearer token authorization method, this endpoint requires the scope &#x27;api:users:read&#x27;.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor When paging is needed, provide the value supplied by the previous API call to bring the following page of records.
  # @option opts [BOOLEAN] :include_avatars Avatars are synthetic users representing Gong employees (CSMs and support providers) when they access your instance. References to avatars&#x27; IDs may be found in the outputs of other API endpoints. This parameter is optional, if not provided avatars will not be included in the results.
  # @return [UsersMetadata]
  describe 'list_users_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
