=begin
#Gong API



OpenAPI spec version: V2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.37
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for GongAPI::CallUsersAccessDto
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CallUsersAccessDto' do
  before do
    # run before each test
    @instance = GongAPI::CallUsersAccessDto.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CallUsersAccessDto' do
    it 'should create an instance of CallUsersAccessDto' do
      expect(@instance).to be_instance_of(GongAPI::CallUsersAccessDto)
    end
  end
  describe 'test attribute "call_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "user_ids"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
