=begin
#Gong API



OpenAPI spec version: V2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.37
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for GongAPI::ContentSelector
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ContentSelector' do
  before do
    # run before each test
    @instance = GongAPI::ContentSelector.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ContentSelector' do
    it 'should create an instance of ContentSelector' do
      expect(@instance).to be_instance_of(GongAPI::ContentSelector)
    end
  end
  describe 'test attribute "context"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["Basic", "Extended", "None"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.context = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "context_timing"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('Array<String>', ["Now", "TimeOfCall"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.context_timing = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "exposed_fields"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
