=begin
#Gong API



OpenAPI spec version: V2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.37
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for GongAPI::UserSettingsHistory
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UserSettingsHistory' do
  before do
    # run before each test
    @instance = GongAPI::UserSettingsHistory.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UserSettingsHistory' do
    it 'should create an instance of UserSettingsHistory' do
      expect(@instance).to be_instance_of(GongAPI::UserSettingsHistory)
    end
  end
  describe 'test attribute "setting"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["active", "emailsImported", "nonRecordedMeetingsImported", "preventEmailImport", "preventWebConferenceRecording", "webConferencesRecorded"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.setting = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "time"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "value"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
